dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.3.1
compiler:
  solc:
    remappings:
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.3.1'
dotenv: .env
networks:
  default: development
  kovan: active
wallets:
  from_key: ${PRIVATE_KEY}